name: Actualizar fecha en el footer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Obtener fecha del último commit
        run: echo "LAST_UPDATE=$(git log -1 --format='%cd' --date=format:'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Reemplazar placeholder en index.html
        run: sed -i "s/{{LAST_UPDATE}}/${{ env.LAST_UPDATE }}/g" index.html

      - name: Commit de los cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Actualizar fecha del footer a ${{ env.LAST_UPDATE }}" || echo "No hay cambios que commitear"
          git push
